#!/usr/bin/env bash

OHMYTMUX_HOME=$HOME/.config/.tmux

cd $HOME/.config

if [[ ! -d $OHMYTMUX_HOME ]]; then
  echo "oh-my-tmux not exist! clone oh-my-tmux repository"
  git clone https://github.com/gpakosz/.tmux.git $OHMYTMUX_HOME
fi

if [[ ! -d tmux ]]; then
	echo "tmux not exist! init tmux submodule"
	git submodule update --init
	mkdir tmux
fi

if [[ ! -h "tmux/tmux.conf" ]]; then
  echo "tmux config not exist! link: ln -s -f $OHMYTMUX_HOME/.tmux.conf $HOME/.config/tmux/tmux.conf"
  ln -s -f $OHMYTMUX_HOME/.tmux.conf $HOME/.config/tmux/tmux.conf
fi

if [[ ! -f "tmux/tmux.conf.local" ]]; then
  echo "tmux config not exist! link: ln -s -f $OHMYTMUX_HOME/.tmux.conf $HOME/.config/tmux/tmux.conf"
  cp "$OHMYTMUX_HOME/.tmux.conf.local" "$HOME/.config/tmux/tmux.conf.local"
fi

echo "# source tmux config file"
tmux source-file $HOME/.config/tmux/tmux.conf.local
