# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# sourcing of local files
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"
plug "$HOME/.config/zsh/mappings.zsh"

# Theme
# plug "zap-zsh/zap-prompt"

# github
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "zap-zsh/vim"



# iterm2_shell_integration
[ -e $HOME/.iterm2_shell_integration.zsh ] && plug "$HOME/.iterm2_shell_integration.zsh" || true

# Load and initialise completion system
autoload -Uz compinit
compinit
